image: node:20

definitions:
  caches:
    npm: ~/.npm

pipelines:
  branches:
    main:
      - step:
          name: Build and Deploy to Vercel
          caches:
            - npm
          script:
            - npm ci
            - npm run build
            - npx vercel deploy --prod --token=$VERCEL_TOKEN
